server:
  port: ${SERVER_PORT}

salt: ${SALT_VALUE}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/console_log?useSSL=false&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true"
    username: "root"
    password: "12345678"
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none #  validate, none
    #defer-datasource-initialization: true #data.sql을 작성할 때 필요
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      # data-locations: classpath:data.sql
      mode: always
  default:
    image:
      address: ${DEFAULT_IMAGE}

  data:
    redis:
      host: redis
      port: 6379

security:
  jwt:
    token:
      secret: ${JWT_TOKEN}
      expire-length:
        access: 3600000
        refresh: 1210000000

cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    s3:
      bucket: ${BUCKET}
    region:
      static: ${REGION}

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"


#logging:
#  level:
#    org:
#      hibernate:
#        SQL: info
#    org.springframework: info
#    console-log: debug